# Copyright Epic Games, Inc. All Rights Reserved.
# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import os
if hasattr(os, 'add_dll_directory'):
    for path in os.environ.get('PATH', '').split(';'):
        try:
            if path:
                os.add_dll_directory(path)
        except Exception:
            pass



from sys import version_info as _swig_python_version_info

import os
import sys

module_loader_cls = None
for cls in sys.meta_path:
    if hasattr(cls, '__name__') and cls.__name__ == 'IsolatedModuleLoader':
        module_loader_cls = cls
        break

if module_loader_cls is None:
    import dna
    import _py3riglogic13_2_7
else:
    dna_rootdir = module_loader_cls.get_module_rootdir('dna') or os.path.dirname(os.path.abspath(__file__))
    dna = module_loader_cls.load_module('dna', rootdir=dna_rootdir)
    _py3riglogic13_2_7 = module_loader_cls.load_module('_py3riglogic13_2_7', rootdir=os.path.dirname(os.path.abspath(__file__)))


try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def with_metaclass(meta, *bases):
    class metaclass(type):

        def __new__(cls, name, this_bases, d):
            return meta(name, bases, d)

        @classmethod
        def __prepare__(cls, name, this_bases):
            return meta.__prepare__(name, bases)
    return type.__new__(metaclass, 'temporary_class', (), {})


if module_loader_cls is not None:
    global_dna = sys.modules.pop('dna', None)
    global_pydna = sys.modules.pop('_py3dna', None)
    local_dna = dna

import dna

if module_loader_cls is not None:
    if '_py3dna' in sys.modules:
        del sys.modules['_py3dna']
    if global_pydna is not None:
        sys.modules['_py3dna'] = global_pydna

    if 'dna' in sys.modules:
        del sys.modules['dna']
    if global_dna is not None:
        sys.modules['dna'] = global_dna

    dna = local_dna

class VersionInfo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    @staticmethod
    def getMajorVersion():
        return _py3riglogic13_2_7.VersionInfo_getMajorVersion()

    @staticmethod
    def getMinorVersion():
        return _py3riglogic13_2_7.VersionInfo_getMinorVersion()

    @staticmethod
    def getPatchVersion():
        return _py3riglogic13_2_7.VersionInfo_getPatchVersion()

    @staticmethod
    def getVersionString():
        return _py3riglogic13_2_7.VersionInfo_getVersionString()

    def __init__(self):
        _py3riglogic13_2_7.VersionInfo_swiginit(self, _py3riglogic13_2_7.new_VersionInfo())
    __swig_destroy__ = _py3riglogic13_2_7.delete_VersionInfo

# Register VersionInfo in _py3riglogic13_2_7:
_py3riglogic13_2_7.VersionInfo_swigregister(VersionInfo)
CalculationType_Scalar = _py3riglogic13_2_7.CalculationType_Scalar
r"""scalar CPU algorithm"""
CalculationType_SSE = _py3riglogic13_2_7.CalculationType_SSE
r"""vectorized (SSE) CPU algorithm"""
CalculationType_AVX = _py3riglogic13_2_7.CalculationType_AVX
r"""
    vectorized (AVX) CPU algorithm (RigLogic must be built with AVX support,
    otherwise it falls back to using the Scalar version)
    """
CalculationType_NEON = _py3riglogic13_2_7.CalculationType_NEON
r"""
    vectorized (NEON) CPU algorithm (RigLogic must be built with NEON support,
    otherwise it falls back to using the Scalar version)
    """
CalculationType_AnyVector = _py3riglogic13_2_7.CalculationType_AnyVector
r"""Pick any available vectorization"""
FloatingPointType_Float = _py3riglogic13_2_7.FloatingPointType_Float
FloatingPointType_HalfFloat = _py3riglogic13_2_7.FloatingPointType_HalfFloat
TranslationType_Vector = _py3riglogic13_2_7.TranslationType_Vector
RotationType_EulerAngles = _py3riglogic13_2_7.RotationType_EulerAngles
RotationType_Quaternions = _py3riglogic13_2_7.RotationType_Quaternions
ScaleType_Vector = _py3riglogic13_2_7.ScaleType_Vector
class Configuration(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    calculationType = property(_py3riglogic13_2_7.Configuration_calculationType_get, _py3riglogic13_2_7.Configuration_calculationType_set)
    floatingPointType = property(_py3riglogic13_2_7.Configuration_floatingPointType_get, _py3riglogic13_2_7.Configuration_floatingPointType_set)
    loadJoints = property(_py3riglogic13_2_7.Configuration_loadJoints_get, _py3riglogic13_2_7.Configuration_loadJoints_set)
    loadBlendShapes = property(_py3riglogic13_2_7.Configuration_loadBlendShapes_get, _py3riglogic13_2_7.Configuration_loadBlendShapes_set)
    loadAnimatedMaps = property(_py3riglogic13_2_7.Configuration_loadAnimatedMaps_get, _py3riglogic13_2_7.Configuration_loadAnimatedMaps_set)
    loadMachineLearnedBehavior = property(_py3riglogic13_2_7.Configuration_loadMachineLearnedBehavior_get, _py3riglogic13_2_7.Configuration_loadMachineLearnedBehavior_set)
    loadRBFBehavior = property(_py3riglogic13_2_7.Configuration_loadRBFBehavior_get, _py3riglogic13_2_7.Configuration_loadRBFBehavior_set)
    loadTwistSwingBehavior = property(_py3riglogic13_2_7.Configuration_loadTwistSwingBehavior_get, _py3riglogic13_2_7.Configuration_loadTwistSwingBehavior_set)
    translationType = property(_py3riglogic13_2_7.Configuration_translationType_get, _py3riglogic13_2_7.Configuration_translationType_set)
    rotationType = property(_py3riglogic13_2_7.Configuration_rotationType_get, _py3riglogic13_2_7.Configuration_rotationType_set)
    scaleType = property(_py3riglogic13_2_7.Configuration_scaleType_get, _py3riglogic13_2_7.Configuration_scaleType_set)
    translationPruningThreshold = property(_py3riglogic13_2_7.Configuration_translationPruningThreshold_get, _py3riglogic13_2_7.Configuration_translationPruningThreshold_set)
    rotationPruningThreshold = property(_py3riglogic13_2_7.Configuration_rotationPruningThreshold_get, _py3riglogic13_2_7.Configuration_rotationPruningThreshold_set)
    scalePruningThreshold = property(_py3riglogic13_2_7.Configuration_scalePruningThreshold_get, _py3riglogic13_2_7.Configuration_scalePruningThreshold_set)

    def __init__(self):
        _py3riglogic13_2_7.Configuration_swiginit(self, _py3riglogic13_2_7.new_Configuration())
    __swig_destroy__ = _py3riglogic13_2_7.delete_Configuration

# Register Configuration in _py3riglogic13_2_7:
_py3riglogic13_2_7.Configuration_swigregister(Configuration)
class Stats(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    calculationType = property(_py3riglogic13_2_7.Stats_calculationType_get, _py3riglogic13_2_7.Stats_calculationType_set)
    floatingPointType = property(_py3riglogic13_2_7.Stats_floatingPointType_get, _py3riglogic13_2_7.Stats_floatingPointType_set)
    rbfSolverCount = property(_py3riglogic13_2_7.Stats_rbfSolverCount_get, _py3riglogic13_2_7.Stats_rbfSolverCount_set)
    mlOperationCount = property(_py3riglogic13_2_7.Stats_mlOperationCount_get, _py3riglogic13_2_7.Stats_mlOperationCount_set)
    psdCount = property(_py3riglogic13_2_7.Stats_psdCount_get, _py3riglogic13_2_7.Stats_psdCount_set)
    blendShapeChannelCount = property(_py3riglogic13_2_7.Stats_blendShapeChannelCount_get, _py3riglogic13_2_7.Stats_blendShapeChannelCount_set)
    animatedMapCount = property(_py3riglogic13_2_7.Stats_animatedMapCount_get, _py3riglogic13_2_7.Stats_animatedMapCount_set)
    jointCount = property(_py3riglogic13_2_7.Stats_jointCount_get, _py3riglogic13_2_7.Stats_jointCount_set)
    jointDeltaValueCount = property(_py3riglogic13_2_7.Stats_jointDeltaValueCount_get, _py3riglogic13_2_7.Stats_jointDeltaValueCount_set)

    def __init__(self):
        _py3riglogic13_2_7.Stats_swiginit(self, _py3riglogic13_2_7.new_Stats())
    __swig_destroy__ = _py3riglogic13_2_7.delete_Stats

# Register Stats in _py3riglogic13_2_7:
_py3riglogic13_2_7.Stats_swigregister(Stats)
class RigInstance(object):
    r"""
    RigInstance contains the instance specific data of a rig.
    Notes: 
        The input / output buffers are all contained within a rig instance.
        It provides functions for setting the level of detail and input control values of a single instance,
        as well as accessors to the output values of joints, blend shapes and animated maps.
        To evaluate / drive the rig instance, it must be passed to the RigLogic::calculate function.
    See also: RigLogic
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def create(rigLogic, memRes=None):
        r"""
        Factory method for the creation of rig instances.
        Notes: 
            Rig instances are all tied to their parent RigLogic instance.
            All rig instances created through a particular RigLogic instance are based on the same DNA.
        Warning: 
            It is not possible to evaluate a rig instance created through one RigLogic instance by another RigLogic instance.
        :type rigLogic: :py:class:`RigLogic`
        :param rigLogic:
                The RigLogic instance upon which this RigInstance should be based.
        :type memRes: :py:class:`MemoryResource`, optional
        :param memRes:
                A custom memory resource to be used for the allocation of the rig instance resources.
        Notes: 
            If a custom memory resource is not given, a default allocation mechanism will be used.
        Warning: 
            User is responsible for releasing the returned pointer by calling destroy.
        See also: destroy
        """
        return _py3riglogic13_2_7.RigInstance_create(rigLogic, memRes)

    @staticmethod
    def destroy(instance):
        r"""
        Method for freeing rig instances.
        See also: create
        """
        return _py3riglogic13_2_7.RigInstance_destroy(instance)

    def getGUIControlCount(self):
        return _py3riglogic13_2_7.RigInstance_getGUIControlCount(self)

    def getGUIControl(self, index):
        return _py3riglogic13_2_7.RigInstance_getGUIControl(self, index)

    def setGUIControl(self, index, value):
        return _py3riglogic13_2_7.RigInstance_setGUIControl(self, index, value)

    def getGUIControlValues(self, *args):
        return _py3riglogic13_2_7.RigInstance_getGUIControlValues(self, *args)

    def getRawControlCount(self):
        return _py3riglogic13_2_7.RigInstance_getRawControlCount(self)

    def getRawControl(self, index):
        return _py3riglogic13_2_7.RigInstance_getRawControl(self, index)

    def setRawControl(self, index, value):
        return _py3riglogic13_2_7.RigInstance_setRawControl(self, index, value)

    def getRawControlValues(self, *args):
        return _py3riglogic13_2_7.RigInstance_getRawControlValues(self, *args)

    def getPSDControlCount(self):
        return _py3riglogic13_2_7.RigInstance_getPSDControlCount(self)

    def getPSDControl(self, index):
        return _py3riglogic13_2_7.RigInstance_getPSDControl(self, index)

    def getPSDControlValues(self):
        return _py3riglogic13_2_7.RigInstance_getPSDControlValues(self)

    def getMLControlCount(self):
        return _py3riglogic13_2_7.RigInstance_getMLControlCount(self)

    def getMLControl(self, index):
        return _py3riglogic13_2_7.RigInstance_getMLControl(self, index)

    def getMLControlValues(self):
        return _py3riglogic13_2_7.RigInstance_getMLControlValues(self)

    def getMLTypeCount(self):
        return _py3riglogic13_2_7.RigInstance_getMLTypeCount(self)

    def getMLOperationSetCount(self, mlTypeIndex):
        return _py3riglogic13_2_7.RigInstance_getMLOperationSetCount(self, mlTypeIndex)

    def getMLOperationCount(self, mlTypeIndex, mlOperationSetIndex):
        return _py3riglogic13_2_7.RigInstance_getMLOperationCount(self, mlTypeIndex, mlOperationSetIndex)

    def getMLMaskValues(self, *args):
        return _py3riglogic13_2_7.RigInstance_getMLMaskValues(self, *args)

    def getRBFControlCount(self):
        return _py3riglogic13_2_7.RigInstance_getRBFControlCount(self)

    def getRBFControl(self, index):
        return _py3riglogic13_2_7.RigInstance_getRBFControl(self, index)

    def getRBFControlValues(self):
        return _py3riglogic13_2_7.RigInstance_getRBFControlValues(self)

    def getJointOutputs(self):
        r"""
        Calculated values for joint transformations.
        Notes: 
            This is just a primitive array of floats, providing access to all the values of all transformations.
        :rtype: rl4::ConstArrayView< float >
        :return: View over the array of values.
        """
        return _py3riglogic13_2_7.RigInstance_getJointOutputs(self)

    def getBlendShapeOutputs(self):
        r"""
        Calculated values for blend shape deformations.
        :rtype: rl4::ConstArrayView< float >
        :return: View over the array of floats.
        """
        return _py3riglogic13_2_7.RigInstance_getBlendShapeOutputs(self)

    def getAnimatedMapOutputs(self):
        r"""
        Calculated values for animated map deformations.
        :rtype: rl4::ConstArrayView< float >
        :return: View over the array of floats.
        """
        return _py3riglogic13_2_7.RigInstance_getAnimatedMapOutputs(self)

    def getLOD(self):
        r"""The current level of details of this instance."""
        return _py3riglogic13_2_7.RigInstance_getLOD(self)

    def setLOD(self, level):
        r"""
        The current level of details of this instance.
        :type level: int
        :param level:
                Value to set for current level of details.
        """
        return _py3riglogic13_2_7.RigInstance_setLOD(self, level)

# Register RigInstance in _py3riglogic13_2_7:
_py3riglogic13_2_7.RigInstance_swigregister(RigInstance)

RigInstanceImpl = RigInstance

class RigInstanceImplReflectionMixin(type):

    def __getattr__(cls, name):
        return getattr(RigInstanceImpl, name)

    def __dir__(cls):
        return [name for name in dir(RigInstanceImpl) if name not in ("create","destroy")]

class RigInstance(with_metaclass(RigInstanceImplReflectionMixin, object)):
    __slots__ = ('_args', '_kwargs', '_instance')

    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        self._instance = RigInstanceImpl.create(*args, **kwargs)

    def __del__(self):
        if self._instance:
            RigInstanceImpl.destroy(self._instance)

    def _in_slots(self, attr):
        for cls in type(self).__mro__:
            if attr in getattr(cls, '__slots__', []):
                return True
        return False

    def __getattr__(self, attr):
        if self._in_slots(attr):
            return object.__getattr__(self, attr)
        return getattr(self._instance, attr)

    def __setattr__(self, attr, value):
        if self._in_slots(attr):
            object.__setattr__(self, attr, value)
        else:
            setattr(self._instance, attr, value)

    def __dir__(self):
        return [name for name in self._instance.__dir__() if name not in ("create","destroy")]

class RigLogic(object):
    r"""
    RigLogic calculates rig output values based on input control values.
    Notes: 
        A single RigLogic instance can create and drive an arbitrary number of rig instances.
        Since the rig instance specific data is located on the RigInstance class, RigLogic
        itself may be considered stateless, and all of it's functions thread-safe.
    See also: RigInstance
    """

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    @staticmethod
    def create(*args):
        r"""
        Factory method for the creation of RigLogic.
        :type reader: :py:class:`Reader`
        :param reader:
                Source from which to copy and optimize DNA data, which is used for rig evaluation
        :type config: :py:class:`Configuration`, optional
        :param config:
                Determines which algorithm implementation is used for rig evaluation and which submodules to load (affects memory
           allocations)
        :type memRes: :py:class:`MemoryResource`, optional
        :param memRes:
                A custom memory resource to be used for allocations.
        Notes: 
            If a custom memory resource is not given, a default allocation mechanism will be used.
        Warning: 
            User is responsible for releasing the returned pointer by calling destroy.
        See also: destroy
        """
        return _py3riglogic13_2_7.RigLogic_create(*args)

    @staticmethod
    def destroy(instance):
        r"""
        Method for freeing RigLogic.
        :type instance: :py:class:`RigLogic`
        :param instance:
                Instance of RigLogic to be freed.
        See also: create
        """
        return _py3riglogic13_2_7.RigLogic_destroy(instance)

    def getConfiguration(self):
        r"""Retrieve the configuration that RigLogic was initialized with."""
        return _py3riglogic13_2_7.RigLogic_getConfiguration(self)

    def getLODCount(self):
        r"""
        Available levels of detail (e.g. 6 which means the following levels are available:
            [0,1,2,3,4,5], where 0 is the LOD with the highest details, and 5 is the LOD with
            lowest details).
        """
        return _py3riglogic13_2_7.RigLogic_getLODCount(self)

    def getRBFSolverIndicesForLOD(self, lod):
        r"""
        List of RBF solver indices that need to be computed on the specified LOD.
        :type lod: int
        :param lod:
                The LOD for which the indices are requested.
        """
        return _py3riglogic13_2_7.RigLogic_getRBFSolverIndicesForLOD(self, lod)

    def getMLOperationIndicesForLOD(self, lod, mlTypeIndex, mlOperationSetIndex):
        r"""
        List of ML operation indices that need to be computed on the specified LOD.
        :type lod: int
        :param lod:
                The LOD for which the indices are requested.
        """
        return _py3riglogic13_2_7.RigLogic_getMLOperationIndicesForLOD(self, lod, mlTypeIndex, mlOperationSetIndex)

    def getBlendShapeChannelIndicesForLOD(self, lod):
        r"""
        List of blend shape channel indices that need to be computed on the specified LOD.
        :type lod: int
        :param lod:
                The LOD for which the indices are requested.
        """
        return _py3riglogic13_2_7.RigLogic_getBlendShapeChannelIndicesForLOD(self, lod)

    def getAnimatedMapIndicesForLOD(self, lod):
        r"""
        List of animated map indices that need to be computed on the specified LOD.
        :type lod: int
        :param lod:
                The LOD for which the indices are requested.
        """
        return _py3riglogic13_2_7.RigLogic_getAnimatedMapIndicesForLOD(self, lod)

    def getJointIndicesForLOD(self, lod):
        r"""
        List of joint indices that need to be computed on the specified LOD.
        :type lod: int
        :param lod:
                The LOD for which the indices are requested.
        """
        return _py3riglogic13_2_7.RigLogic_getJointIndicesForLOD(self, lod)

    def getNeutralJointValues(self):
        r"""
        Neutral values of joint transformations.
        Notes: 
            These is just a primitive array of floats, providing access to all the values of all transformations.
        :rtype: rl4::ConstArrayView< float >
        :return: View over the array of values.
        """
        return _py3riglogic13_2_7.RigLogic_getNeutralJointValues(self)

    def getJointVariableAttributeIndices(self, lod):
        r"""All joint output indices concatenated into a single chunk per each LOD."""
        return _py3riglogic13_2_7.RigLogic_getJointVariableAttributeIndices(self, lod)

    def getJointGroupCount(self):
        r"""
        Number of joint groups present in the entire joint matrix.
        See also: calculateJoints
        """
        return _py3riglogic13_2_7.RigLogic_getJointGroupCount(self)

    def getRBFSolverCount(self):
        r"""
        Number of RBF solvers for driving RBF behavior.
        See also: calculateRBFBehavior
        """
        return _py3riglogic13_2_7.RigLogic_getRBFSolverCount(self)

    def getTwistCount(self):
        r"""Number of twist setups in body behavior."""
        return _py3riglogic13_2_7.RigLogic_getTwistCount(self)

    def getSwingCount(self):
        r"""Number of swing setups in body behavior."""
        return _py3riglogic13_2_7.RigLogic_getSwingCount(self)

    def getMeshCount(self):
        r"""Number of meshes."""
        return _py3riglogic13_2_7.RigLogic_getMeshCount(self)

    def getMeshRegionCount(self, meshIndex):
        r"""Number of regions within the specified mesh."""
        return _py3riglogic13_2_7.RigLogic_getMeshRegionCount(self, meshIndex)

    def getMLTypeCount(self):
        r"""
        Number of ML model types.
        See also: calculateMLControls
        """
        return _py3riglogic13_2_7.RigLogic_getMLTypeCount(self)

    def getMLOperationSetCount(self, mlTypeIndex):
        r"""Number of ML operation sets for the specified type."""
        return _py3riglogic13_2_7.RigLogic_getMLOperationSetCount(self, mlTypeIndex)

    def getMLOperationCount(self, mlTypeIndex, mlOperationSetIndex):
        r"""
        Number of ML operation for the specified type.
        Notes: This can be thought of as parallel instances of a series of operations.
        """
        return _py3riglogic13_2_7.RigLogic_getMLOperationCount(self, mlTypeIndex, mlOperationSetIndex)

    def mapGUIToRawControls(self, instance):
        r"""
        Maps GUI controls to raw controls.
        Notes: 
            This method may be called after either RigInstance::setGUIControlValues or RigInstance::setGUIControl was used.
        """
        return _py3riglogic13_2_7.RigLogic_mapGUIToRawControls(self, instance)

    def mapRawToGUIControls(self, instance):
        r"""
        Maps raw controls to GUI controls.
        Notes: 
            This method may be called after either RigInstance::setRawControlValues or RigInstance::setRawControl was used.
        """
        return _py3riglogic13_2_7.RigLogic_mapRawToGUIControls(self, instance)

    def calculateMLControls(self, instance):
        r"""
        Calculate controls driving the machine learned behavior of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose controls for driving machine learned behavior are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateMLControls(self, instance)

    def calculateMLOperation(self, instance, mlTypeIndex, mlOperationSetIndex, mlOperationIndex):
        r"""
        Calculate controls driving the machine learned behavior of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose controls for driving machine learned behavior are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateMLOperation(self, instance, mlTypeIndex, mlOperationSetIndex, mlOperationIndex)

    def calculateRBFControls(self, instance):
        r"""
        Calculate controls driving the RBF behavior of the of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose controls for driving machine learned behavior are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateRBFControls(self, instance)

    def calculateRBFSolver(self, instance, solverIndex):
        r"""
        Calculate controls driving the RBF behavior of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose controls for RBF behavior are to be calculated.
        :type solverIndex: int
        :param solverIndex:
                The RBF solver whose outputs need to be calculated.
        Warning: 
            The index must be less than the value returned by getRBFSolverCount.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateRBFSolver(self, instance, solverIndex)

    def calculatePSDControls(self, instance):
        r"""
        Calculate only the PSD control values of the rig.
        Notes: 
            Based on the set or computed raw control values, calculate the PSD outputs.
            The raw control values, followed by the PSD, ML and RBF values represent the input values of the rig.

            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose outputs are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculatePSDControls(self, instance)

    def calculateJoints(self, instance):
        r"""
        Calculate only the joint outputs of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose outputs are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateJoints(self, instance)

    def calculateJointGroup(self, instance, jointGroupIndex):
        r"""
        Calculate individual joint groups.
        Notes: 
            It's intended to be used in a multi-threaded environment, such that the calculatin of all joint groups
            is performed by several threads, instead of computing all at once.

            This is considered as an expert usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose outputs are to be calculated.
        :type jointGroupIndex: int
        :param jointGroupIndex:
                A joint group's position in the zero-indexed array of joint groups.
        Warning: 
            The index must be less than the value returned by getJointGroupCount.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateJointGroup(self, instance, jointGroupIndex)

    def calculateBlendShapes(self, instance):
        r"""
        Calculate only the blend shape channel weights of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose blend shape channel weights are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateBlendShapes(self, instance)

    def calculateAnimatedMaps(self, instance):
        r"""
        Calculate only the animated map outputs of the rig.
        Notes: 
            This is considered as an advanced usage use case.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose outputs are to be calculated.
        See also: calculate
        """
        return _py3riglogic13_2_7.RigLogic_calculateAnimatedMaps(self, instance)

    def calculate(self, instance):
        r"""
        Calculate outputs for joints, blend shapes, and animated maps.
        Notes: 
            It performs a complete evaluation of the rig, computing all the output values in the following order:
              - Calculate input values (raw controls + PSDs)
              - Calculate joint output values
              - Calculate blend shape output values
              - Calculate animated map output values
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance whose outputs are to be calculated.
        """
        return _py3riglogic13_2_7.RigLogic_calculate(self, instance)

    def collectCalculationStats(self, instance, stats):
        r"""
        Collect stats that summarize the overall amount of data that participate in computation for the current LOD.
        :type instance: :py:class:`RigInstance`
        :param instance:
                The rig instance which provides the current LOD to compute the necessary stats.
        :type stats: :py:class:`Stats`
        :param stats:
                The object into which the collected data will be written.
        """
        return _py3riglogic13_2_7.RigLogic_collectCalculationStats(self, instance, stats)

# Register RigLogic in _py3riglogic13_2_7:
_py3riglogic13_2_7.RigLogic_swigregister(RigLogic)

RigLogicImpl = RigLogic

class RigLogicImplReflectionMixin(type):

    def __getattr__(cls, name):
        return getattr(RigLogicImpl, name)

    def __dir__(cls):
        return [name for name in dir(RigLogicImpl) if name not in ("create","destroy")]

class RigLogic(with_metaclass(RigLogicImplReflectionMixin, object)):
    __slots__ = ('_args', '_kwargs', '_instance')

    def __init__(self, *args, **kwargs):
        self._args = args
        self._kwargs = kwargs
        self._instance = RigLogicImpl.create(*args, **kwargs)

    def __del__(self):
        if self._instance:
            RigLogicImpl.destroy(self._instance)

    def _in_slots(self, attr):
        for cls in type(self).__mro__:
            if attr in getattr(cls, '__slots__', []):
                return True
        return False

    def __getattr__(self, attr):
        if self._in_slots(attr):
            return object.__getattr__(self, attr)
        return getattr(self._instance, attr)

    def __setattr__(self, attr, value):
        if self._in_slots(attr):
            object.__setattr__(self, attr, value)
        else:
            setattr(self._instance, attr, value)

    def __dir__(self):
        return [name for name in self._instance.__dir__() if name not in ("create","destroy")]


